services:
    web-server:
        image: nginx
        volumes:
            - ./dist:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 20012:80
